/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.38
 * Generated at: 2019-12-17 11:24:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import modelBean.UtenteBean;
import modelBean.PacchettoBean;
import modelBean.AmministratoreBean;

public final class HomePage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/Footer.jsp", Long.valueOf(1576578070010L));
    _jspx_dependants.put("/BarraCategoria.jsp", Long.valueOf(1576577017469L));
    _jspx_dependants.put("/header.jsp", Long.valueOf(1576581705859L));
    _jspx_dependants.put("/BarraNavigazione.jsp", Long.valueOf(1576581347938L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("modelBean.PacchettoBean");
    _jspx_imports_classes.add("modelBean.AmministratoreBean");
    _jspx_imports_classes.add("modelBean.UtenteBean");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<head>\r\n");
      out.write("\t");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/HomePage.css\">\r\n");
      out.write("    <link rel = \"stylesheet\" href = \"css/login.css\">\r\n");
      out.write("   \t<link href=\"https://fonts.googleapis.com/css?family=Mali&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Dancing+Script\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Courgette&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Coming+Soon&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Karma\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.8.2/css/all.css\" integrity=\"sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay\" crossorigin=\"anonymous\">  \r\n");
      out.write("\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\" integrity=\"sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"./js/login.js\"></script>\r\n");
      out.write("    <script src=\"./js/menuResponse.js\"></script>\r\n");
      out.write("    <script src=\"./js/jquery.nicescroll.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/UserArea.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/barraCategoria.js\"></script>\r\n");
      out.write("</head>");
      out.write("\r\n");
      out.write("\t<link rel=\"shortcut icon\" type = \"image/ico\" href=\"img/utility/Logo.ico\"/>\r\n");
      out.write("\t<title>StudyMe</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class =\"container\">\r\n");
      out.write(" \t");
      out.write("<!-- Barra di navigazione -->\r\n");
      out.write("\r\n");

	UtenteBean loggedUser = (UtenteBean) session.getAttribute("User");
	AmministratoreBean administrator = (AmministratoreBean) session.getAttribute("Amministratore");

	HttpSession sessione = request.getSession();
	ArrayList<PacchettoBean> carrello = (ArrayList<PacchettoBean>) sessione.getAttribute("carrello");
	if(carrello == null){
		carrello = new ArrayList<PacchettoBean>();
	}
	
	String initial = null;

	if (loggedUser != null) {
		initial = loggedUser.getNomeUtente().substring(0, 2);
	}

	if (administrator != null) {
		initial = administrator.getNomeAmministratore().substring(0, 2);
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"navbar\">\r\n");
      out.write("\t<div id=\"logo\">\r\n");
      out.write("\t\t<div class=\"navbar-item\" id=\"logo-item\">\r\n");
      out.write("\t\t\t<div class=\"navbar-item-image\">\r\n");
      out.write("\t\t\t\t<a href=\"HomePage.jsp\"><img src=\"./img/utility/Logo sito.png\"\r\n");
      out.write("\t\t\t\t\talt=\"logo\"></a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"navbar-item-description\">StudyMe</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<form id=\"ricerca\" method=\"GET\" action=\"SearchServlet\">\r\n");
      out.write("\t\t<i class=\"fas fa-search\"></i> <input type=\"Text\" name=\"argument\"\r\n");
      out.write("\t\t\tplaceholder=\"Cosa vuoi imparare oggi ?\">\r\n");
      out.write("\t</form>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"carrello\">\r\n");
      out.write("\t\t<nav>\r\n");
      out.write("\t\t\t<ul class=\"nav\">\r\n");
      out.write("\t\t\t\t");

					if (administrator != null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"navbar-item login\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"navbar-item-image\" onClick=\"redirectUserArea()\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cerchio\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h1>");
      out.print(initial);
      out.write("</h1>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t");

					} else if (loggedUser != null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"navbar-item login\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"navbar-item-image\" onClick=\"redirectUserArea()\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cerchio\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h1>");
      out.print(initial);
      out.write("</h1>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"navbar-item login\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"navbar-item-image\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"LibreriaServlet\"><img src=\"./img/utility/libreria.png\" alt=\"logo\"></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"navbar-item-description\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"LibreriaServlet\"><div id=\"pulsante-accedi\" onClick=\"\">Lezioni</div></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"navbar-item\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"navbar-item-image\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href = \"Cart.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id = \"numberIncrement\" style = \"right: 10px;\">");
      out.print(carrello.size());
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src = \"./img/utility/carrello.png\" alt=\"logo\">\r\n");
      out.write("\t\t\t\t\t\t\t</a>\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"Cart.jsp\"><div class=\"navbar-item-description\">Carrello</div></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"navbar-item login\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"navbar-item-image\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"./img/utility/user.png\" alt=\"logo\" id=\"loginImage\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonClick=\"mostraLogin()\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"navbar-item-description\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"pulsante-accedi\" onClick=\"mostraLogin()\">Accedi</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"navbar-item\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"navbar-item-image\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"Cart.jsp\"><img src=\"./img/utility/carrello.png\" alt=\"logo\"></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<div id = \"numberIncrement\" style = \"right: 10px;\">");
      out.print(carrello.size());
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"CarrelloServlet\"><div class=\"navbar-item-description\">Carrello</div></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<i class=\"fas fa-bars\" onclick=\"openNav()\"></i>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Barra di navigazione resposive -->\r\n");
      out.write("<div id=\"responsive-bar\">\r\n");
      out.write("\t<div id=\"lateral\">\r\n");
      out.write("\t\t<i class=\"closebtn\" onclick=\"closeNav()\">&times;</i>\r\n");
      out.write("\t\t<nav>\r\n");
      out.write("\t\t\t<ul class=\"navLateral\">\r\n");
      out.write("\t\t\t\t");

					if (administrator != null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div id=\"formSearch\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-search\" onClick=\"ShowSearchBar()\"></i>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"navbar-item-description search\"\r\n");
      out.write("\t\t\t\t\t\t\tonClick=\"ShowSearchBar()\">Cerca</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"formSearchResponse\">\r\n");
      out.write("\t\t\t\t\t\t<form id=\"ricercaResponsive\" method=\"GET\" action=\"SearchServlet\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fas fa-times\" onClick=\"HideSearchBar()\"></i> <input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"Text\" name=\"argument\" placeholder=\"Cerca pacchetti\">\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"navbar-item login\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"navbar-item-image\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fas fa-plus-square\" onClick=\"redirectUserArea()\"></i>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"navbar-item-description\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"pulsante-accedi\" onClick=\"redirectUserArea()\">Aggiungi pacchetti</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t");
if(request.getRequestURI().equals("/StudyMe/UserArea.jsp")){
      out.write("\r\n");
      out.write("\t\t\t\t<li>\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"navbar-item login ordini\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"navbar-item-image\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fas fa-money-check-alt\" onClick= \"showOrdersAdministrator()\"></i>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"navbar-item-description\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"pulsante-accedi\" onClick= \"showOrdersAdministrator()\">Ordini</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\t\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t");

					} else if (loggedUser != null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"navbar-item login\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"navbar-item-image\" onClick=\"redirectUserArea()\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"cerchio\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h1>");
      out.print(initial);
      out.write("</h1>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t");
if(request.getRequestURI().equals("/StudyMe/UserArea.jsp")){
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t<li>\t\t\t\r\n");
      out.write("\t\t\t\t\t<div class=\"navbar-item\">\t\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"navbar-item-image\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fas fa-money-check-alt\" onClick= \"showOrders()\"></i>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"navbar-item-description\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"pulsante-accedi\" onClick= \"showOrders()\">Ordini</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t");
}
      out.write("\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div id=\"formSearch\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-search\" onClick=\"ShowSearchBar()\"></i>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"navbar-item-description search\"\r\n");
      out.write("\t\t\t\t\t\t\tonClick=\"ShowSearchBar()\">Cerca</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"formSearchResponse\">\r\n");
      out.write("\t\t\t\t\t\t<form id=\"ricercaResponsive\" method=\"GET\" action=\"SearchServlet\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fas fa-times\" onClick=\"HideSearchBar()\"></i> <input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"Text\" name=\"argument\" placeholder=\"Cerca pacchetti\">\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"navbar-item login\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"navbar-item-image\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"LibreriaServlet\"><img src=\"./img/utility/libreria.png\" alt=\"logo\"></a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"LibreriaServlet\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"navbar-item-description\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id=\"pulsante-accedi\" >Lezioni</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"navbar-item\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"navbar-item-image\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href = \"Cart.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id = \"numberIncrement\" style = \"right: 30px;\">");
      out.print(carrello.size());
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src = \"./img/utility/carrello.png\" alt=\"logo\">\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a href = \"Cart.jsp\"><div class=\"navbar-item-description\">Carrello</div></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t");

					} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div id=\"formSearch\">\r\n");
      out.write("\t\t\t\t\t\t<i class=\"fas fa-search\" onClick=\"ShowSearchBar()\"></i>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"navbar-item-description search\"\r\n");
      out.write("\t\t\t\t\t\t\tonClick=\"ShowSearchBar()\">Cerca</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div id=\"formSearchResponse\">\r\n");
      out.write("\t\t\t\t\t\t<form id=\"ricercaResponsive\" method=\"GET\" action=\"SearchServlet\">\r\n");
      out.write("\t\t\t\t\t\t\t<i class=\"fas fa-times\" onClick=\"HideSearchBar()\"></i> <input\r\n");
      out.write("\t\t\t\t\t\t\t\ttype=\"Text\" name=\"argument\" placeholder=\"Cerca pacchetti\">\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"navbar-item login\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"navbar-item-image\">\r\n");
      out.write("\t\t\t\t\t\t\t<img src=\"./img/utility/user.png\" alt=\"logo\" id=\"loginImage\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonClick=\"mostraLogin()\">\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"navbar-item-description\">\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"pulsante-accedi\" onClick=\"mostraLogin()\">Accedi</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t<div class=\"navbar-item\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"navbar-item-image\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href = \"Cart.jsp\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div id = \"numberIncrement\" style = \"right: 30px;\">");
      out.print(carrello.size());
      out.write("</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src = \"./img/utility/carrello.png\" alt=\"logo\">\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<a href = \"Cart.jsp\"><div class=\"navbar-item-description\">Carrello</div></a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t");

					if (loggedUser != null || administrator != null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<a href=\"LogoutServlet\">\r\n");
      out.write("\t\t\t\t\t<li><i class=\"fas fa-sign-out-alt\"></i>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"navbar-item-description\">Logout</div></li>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Login -->\r\n");
      out.write("<div class=\"sfondo-login\">\r\n");
      out.write("\t<div id=\"close-icon\" onClick=\"nascondi()\">\r\n");
      out.write("\t\t<i class=\"far fa-times-circle\"></i>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-login\">\r\n");
      out.write("\t\t<div class=\"form\">\r\n");
      out.write("\t\t\t<h2>Accedi</h2>\r\n");
      out.write("\t\t\t<div id=\"messageError\"></div>\r\n");
      out.write("\t\t\t<form name=\"login\">\r\n");
      out.write("\t\t\t\t<label for=\"uname\"><b>Nome utente</b></label> <input type=\"text\"\r\n");
      out.write("\t\t\t\t\tplaceholder=\"Inserisci nome utente\" name=\"NomeUtente\" id=\"myName\"\r\n");
      out.write("\t\t\t\t\trequired> <label for=\"psw\"><b>Password</b></label>\r\n");
      out.write("\t\t\t\t<div class=\"input-with-icon\">\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" placeholder=\"Inserisci password\"\r\n");
      out.write("\t\t\t\t\t\tname=\"Password\" id=\"myPass\" required> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fas fa-eye-slash\" onclick=\"togglePassword(event)\"></i>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<span class=\"dim\" onclick=\"mostraRecuperoPassword()\">Password\r\n");
      out.write("\t\t\t\t\tdimenticata ?</span>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<button type=\"submit\">Accedi</button>\r\n");
      out.write("\t\t\t\t<span class=\"remb\"> <label> <input type=\"checkbox\"\r\n");
      out.write("\t\t\t\t\t\tid=\"remember\">Ricordami\r\n");
      out.write("\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t\t<div class=\"footer\">Non sei ancora registrato?</div>\r\n");
      out.write("\t\t\t<div class=\"footer\">\r\n");
      out.write("\t\t\t\t<div id=\"pulsante-registrati\" onClick=\"mostraRegistrazione()\">\r\n");
      out.write("\t\t\t\t\tRegistrati</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Registrazione -->\r\n");
      out.write("<div class=\"sfondo-login registrazione\">\r\n");
      out.write("\t<div id=\"close-icon\" onClick=\"nascondi()\">\r\n");
      out.write("\t\t<i class=\"far fa-times-circle\"></i>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"container-login registrazione\">\r\n");
      out.write("\t\t<div class=\"form\">\r\n");
      out.write("\t\t\t<h2>Registrati</h2>\r\n");
      out.write("\t\t\t<div id=\"signUpMessageError\"></div>\r\n");
      out.write("\t\t\t<form name=\"sign-up\">\r\n");
      out.write("\t\t\t\t<label for=\"surname\"><b>Nome Utente</b></label><br> <input\r\n");
      out.write("\t\t\t\t\ttype=\"text\" placeholder=\"Inserisci nome utente\" name=\"NomeUtente\"\r\n");
      out.write("\t\t\t\t\trequired id=\"newName\"> <label for=\"email\"><b>Email</b></label><br>\r\n");
      out.write("\t\t\t\t<input type=\"email\" placeholder=\"Inserisci email\" name=\"Email\"\r\n");
      out.write("\t\t\t\trequired id=\"newEmail\"> <label for=\"password\"\r\n");
      out.write("\t\t\t\t\tclass=\"control-label\"><b>Password</b></label>\r\n");
      out.write("\t\t\t\t<div class=\"input-with-icon\">\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" minlength=\"8\" placeholder=\"Inserisci password\"\r\n");
      out.write("\t\t\t\t\t\tname=\"Password\" id=\"regPass\" required> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fas fa-eye-slash\" onclick=\"togglePassword(event)\"></i>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<label for=\"confPass\"><b>Conferma password</b></label>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"input-with-icon\">\r\n");
      out.write("\t\t\t\t\t<input type=\"password\" minlength=\"8\" placeholder=\"Reinserisci password\"\r\n");
      out.write("\t\t\t\t\t\tname=\"Conf_Password\" id=\"regPassRepeat\" required> <i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fas fa-eye-slash\" onclick=\"togglePassword(event)\"></i>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<button type=\"submit\">Registrati</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"footer\">Sei gi&agrave; registrato?</div>\r\n");
      out.write("\t\t\t\t<div class=\"footer\">\r\n");
      out.write("\t\t\t\t\t<div id=\"new-pulsante-accedi\" onClick=\"mostraLogin()\">Accedi\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Recupera password -->\r\n");
      out.write("<div class=\"sfondo-login recuperoPassword\">\r\n");
      out.write("\t<div id=\"close-icon\" onClick=\"nascondi()\">\r\n");
      out.write("\t\t<i class=\"far fa-times-circle\"></i>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container-login recuperoPassword\">\r\n");
      out.write("\t\t<div class=\"form\">\r\n");
      out.write("\t\t\t<h2 id=\"recovery\">Recupero password</h2>\r\n");
      out.write("\t\t\t<div id=\"signUpMessageError\"></div>\r\n");
      out.write("\t\t\t<form name=\"passRecovery\" id=\"formRecovery\">\r\n");
      out.write("\t\t\t\t<label for=\"email\"><b>Inserisci la tua mail</b></label><br> <input\r\n");
      out.write("\t\t\t\t\ttype=\"email\" placeholder=\"es: marioRossi@libero.it\" name=\"Email\"\r\n");
      out.write("\t\t\t\t\trequired id=\"emailF\">\r\n");
      out.write("\t\t\t\t<button type=\"submit\">Invio</button>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write("  \r\n");
      out.write("\t");
      out.write("<div class = \"barraCategorie\">\r\n");
      out.write("\t<a href = \"ServletCatalogo?categoria=Sviluppo\"> \r\n");
      out.write("\t\t<span class = \"cartaCategoria\" style=\"background-image: url('img/category-small/sviluppo2.jpg')\">\r\n");
      out.write("\t\t<span class = \"sfondo\"></span>\r\n");
      out.write("\t\t\t<h1>Sviluppo</h1>\r\n");
      out.write("\t\t</span>\r\n");
      out.write("\t</a>\r\n");
      out.write("\r\n");
      out.write("\t<a href = \"ServletCatalogo?categoria=Fotografia\"> \r\n");
      out.write("\t\t<span class = \"cartaCategoria\" style=\"background-image: url('img/category-small/fotografia2.jpg')\">\r\n");
      out.write("\t\t<span class = \"sfondo\"></span>\r\n");
      out.write("\t\t\t<h1>Fotografia</h1>\r\n");
      out.write("\t\t</span>\r\n");
      out.write("\t</a>\r\n");
      out.write("\r\n");
      out.write("\t<a href = \"ServletCatalogo?categoria=Musica\"> \r\n");
      out.write("\t\t<span class = \"cartaCategoria\" style=\"background-image: url('img/category-small/musica2.jpg')\">\r\n");
      out.write("\t\t<span class = \"sfondo\"></span>\r\n");
      out.write("\t\t\t<h1>Musica</h1>\r\n");
      out.write("\t\t</span>\r\n");
      out.write("\t</a>\r\n");
      out.write("\r\n");
      out.write("\t<a href = \"ServletCatalogo?categoria=Informatica\"> \r\n");
      out.write("\t\t<span class = \"cartaCategoria\" style=\"background-image: url('img/category-small/informatica2.jpg')\">\r\n");
      out.write("\t\t<span class = \"sfondo\"></span>\r\n");
      out.write("\t\t\t<h1>Informatica</h1>\r\n");
      out.write("\t\t</span>\r\n");
      out.write("\t</a>\r\n");
      out.write("\r\n");
      out.write("\t<a href = \"ServletCatalogo?categoria=Produttivita\"> \r\n");
      out.write("\t\t<span class = \"cartaCategoria\" style=\"background-image: url('img/category-small/Produttivita.jpg')\">\r\n");
      out.write("\t\t<span class = \"sfondo\"></span>\r\n");
      out.write("\t\t\t<h1>Produttivita'</h1>\r\n");
      out.write("\t\t</span>\r\n");
      out.write("\t</a>\r\n");
      out.write("\r\n");
      out.write("\t<a href = \"ServletCatalogo?categoria=Design\"> \r\n");
      out.write("\t\t<span class = \"cartaCategoria\" style=\"background-image: url('img/category-small/design.jpg')\">\r\n");
      out.write("\t\t<span class = \"sfondo\"></span>\r\n");
      out.write("\t\t\t<h1>Design</h1>\r\n");
      out.write("\t\t</span>\r\n");
      out.write("\t</a>\r\n");
      out.write("\r\n");
      out.write("\t<a href = \"ServletCatalogo?categoria=Insegnamento\"> \r\n");
      out.write("\t\t<span class = \"cartaCategoria\" style=\"background-image: url('img/category-small/Insegnamento.jpg')\">\r\n");
      out.write("\t\t<span class = \"sfondo\"></span>\r\n");
      out.write("\t\t\t<h1>Insegnamento</h1>\r\n");
      out.write("\t\t</span>\r\n");
      out.write("\t</a>\r\n");
      out.write("\r\n");
      out.write("\t<a href = \"ServletCatalogo?categoria=Business\"> \r\n");
      out.write("\t\t<span class = \"cartaCategoria\" style=\"background-image: url('img/category-small/Business.jpg')\">\r\n");
      out.write("\t\t<span class = \"sfondo\"></span>\r\n");
      out.write("\t\t\t<h1>Business</h1>\r\n");
      out.write("\t\t</span>\r\n");
      out.write("\t</a>\r\n");
      out.write("</div>");
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("    <!-- Slide Show -->\r\n");
      out.write("\t<div class = \"slideshow-container\">\r\n");
      out.write("\t\t<div class=\"slideshow\" style=\"background: url('img/slideshow/Home1.jpg')\">\r\n");
      out.write("\t\t\t<div class = \"text-wrapper\">\r\n");
      out.write("\t\t\t\t<div class = \"slideshow-frase\">Non abbandonare le tue passioni</div>\r\n");
      out.write("\t\t\t\t<div class = \"slideshow-sottofrase\">Essere appassionati di qualcosa &egrave; la caratteristica pi&ugrave; bella che si pu&ograve; sviluppare.</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"slideshow\" style=\"background: url('img/slideshow/Home2.jpg')\">\r\n");
      out.write("\t\t     <div class = \"text-wrapper\">\r\n");
      out.write("\t\t\t      <div class = \"slideshow-frase\">StudyMe in qualsiasi momento della giornata</div>\r\n");
      out.write("\t\t\t           <div class = \"slideshow-sottofrase\">Impara quando e ovunque tu voglia, la prima lezione la offriamo noi.</div>\r\n");
      out.write("\t\t\t      </div>\r\n");
      out.write("\t\t     </div>\r\n");
      out.write("\t\t            \r\n");
      out.write("\t\t<div class=\"slideshow\" style=\"background: url('img/slideshow/Home3.jpg')\">\r\n");
      out.write("\t\t     <div class = \"text-wrapper\">\r\n");
      out.write("\t\t\t       <div class = \"slideshow-frase\">Investi su di te</div>\r\n");
      out.write("\t\t\t       <div class = \"slideshow-sottofrase\">Con un corso aggiunto ogni giorno, &egrave; garantito che tu possa trovare quello che fa per te.</div>\r\n");
      out.write("\t\t     </div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t        \r\n");
      out.write("\t<!-- Chi siamo -->\r\n");
      out.write("\t<div class = \"whoWeAre\">\r\n");
      out.write("\t\t<h1>Chi siamo?</h1>\r\n");
      out.write("\t        <!--Modificare info-->\r\n");
      out.write("\t\t\t<div class = \"grid-container\">\r\n");
      out.write("\t\t\t\t<div class = \"cell medium\">\r\n");
      out.write("\t\t\t\t\t<h1>La nostra missione</h1>\r\n");
      out.write("\t\t\t\t\t<p>StudyMe &egrave; un sito web nato con l&apos; idea di rendere pi&ugrave; semplice e rapido il modo di apprendere per chi durante la quotidianit&agrave; non ha tempo di frequentare dei veri e propri corsi d&apos;apprendimento oppure per la semplice volont&agrave; di aumentare le proprie conoscenze. </p>\r\n");
      out.write("\t             </div>\r\n");
      out.write("\t\r\n");
      out.write("\t              <div class = \"cell medium\">\r\n");
      out.write("\t                  <h1>La nostra essenza</h1>\r\n");
      out.write("\t                  <p>Con StudyMe puoi usufrire di videolezioni utili alla comprensione dell&apos;argomento da te desiderato, in qualsiasi momento della giornata e in qualsiasi luogo, basta solo un dispositivo connesso ad internet che abbia accesso ad un browser. </p>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t\r\n");
      out.write("\t              <div class = \"cell medium\">\r\n");
      out.write("\t                   <h1>Le nostre promesse</h1>\r\n");
      out.write("\t                   <p>StudyMe promette ai propri studenti una conoscenza completa su ogni argomento utile non solo per inseguire una semplice passione, ma anche per aumentare le possibilit&agrave; di lavoro. Per assicurarti che tu abbia intrapreso il corso giusto, la prima lezione la offriamo noi.</p>\r\n");
      out.write("\t              </div>\r\n");
      out.write("\t\r\n");
      out.write("\t               <div class = \"cell medium\">\r\n");
      out.write("\t                   <h1>La nostra atmosfera</h1>\r\n");
      out.write("\t                   <p>StudyMe offre una sezione di registrazione per i nuovi utenti e una sezione di accesso per gli utenti gi&agrave; registrati. Alla registrazione dell&apos;utente sar&agrave; disponibile un area personale nella quale saranno visibili i video dei pacchetti acquistati. Una volta che un pacchetto &egrave; presente nell&apos;area personale dell&apos;utente, le video lezioni possono essere consultate senza alcun limite. Una sezione ricerca render&agrave; per l&apos;utente pi&ugrave; facile ed efficiente la ricerca di un pacchetto.</p>\r\n");
      out.write("\t               </div>\r\n");
      out.write("\t       </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t        \r\n");
      out.write("\t<!-- Lista vantaggi -->\r\n");
      out.write("\t<div class = \"listaVantaggi-container\">\r\n");
      out.write("\t\t<h1>Perch&egrave; scegliere noi ?</h1>\r\n");
      out.write("\t\r\n");
      out.write("\t \t<div class=\"grid-container\">\r\n");
      out.write("\t         <div class = \"cell\">\r\n");
      out.write("\t\t\t\t<i class=\"fas fa-piggy-bank\"></i>\r\n");
      out.write("\t            <h1>Risparmia il tuo denaro</h1>\r\n");
      out.write("\t            <p>Con StudyMe non avrai pi&igrave; bisogno di ripetizioni, spostamenti o libri. L&apos;unica cosa che ti occorre &egrave; un dispositivo con accesso alla rete.</p>\r\n");
      out.write("\t         </div>\r\n");
      out.write("\t                \r\n");
      out.write("\t         <div class = \"cell\">\r\n");
      out.write("\t            <i class=\"fas fa-heart\"></i>\r\n");
      out.write("\t            <h1>Insegui i tuoi sogni</h1>\r\n");
      out.write("\t            <p>StudyMe mette a disposizione ogni giorno nuove video lezioni di ogni categoria. Qualsiasi sia la tua passione, sar&agrave; semplice seguirla.</p>\r\n");
      out.write("\t         </div>\r\n");
      out.write("\t\r\n");
      out.write("\t         <div class = \"cell odd\">\r\n");
      out.write("\t            <i class=\"fas fa-clock\"></i>\r\n");
      out.write("\t            <h1>Non temere il tempo</h1>\r\n");
      out.write("\t            <p>Con StudyMe puoi apprendere a qualsiasi orario tu voglia, sar&agrave; sempre l&igrave; a tua disposizione.</p>\r\n");
      out.write("\t         </div>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t </div>\r\n");
      out.write("\t   ");
      out.write("<div class = \"footer-container\">\r\n");
      out.write("\t<div class = \"grid-container light-font-color\">\r\n");
      out.write("\t\t<div class = \"cell\">\r\n");
      out.write("\t\t\t<i class=\"fas fa-map-marker-alt small-font\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<a href=\"https://goo.gl/maps/RcSBNEArTeUgF8Se8\" target= \"_blank\">\r\n");
      out.write("\t\t\t\t\t\tVia Giovanni Paolo II, 132, <br> \r\n");
      out.write("\t\t\t\t\t\t84084 Fisciano SA\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</i>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class = \"cell\">\r\n");
      out.write("\t\t\t<i class=\"fas fa-phone small-font\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t<a href=\"tel:+089 961111\">\r\n");
      out.write("\t\t\t\t\t\t+089 961111\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write(" \t\t\t</i>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class = \"cell odd\">\r\n");
      out.write("\t\t\t<i class=\"far fa-envelope small-font\">\r\n");
      out.write("\t\t\t\t<p>  \r\n");
      out.write("\t\t\t\t\t<a href = \"mailto: info@studyme.com\">is.studyMe@gmail.com</a> \r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</i>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>");
      out.write(" \r\n");
      out.write("    </div>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"./js/scorrimentoFoto.js\"></script>\r\n");
      out.write("</body>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
